project:
  type: website

website:
  title: "Genome-Wide Association Studies"
  google-analytics: 
    tracking-id: "G-EXW13D5861"
    anonymize-ip: true
  navbar:
    logo: /img/logo.png
    left:
      - href: develop/index.qmd
        text: Home
      - text: Access
        href: access/setup.qmd
      - text: Tutorials
        href: develop/general-intro.qmd

  sidebar:
    - title: "Introduction"
      style: "docked"
      search: true
      contents:
        - href: develop/general-intro.qmd
          text: Instructions
        - section: "Introduction"
          contents:
            - develop/GWAS0-geneticTheory.qmd
            - develop/GWAS1-WhatIsAGWAS.qmd
            - develop/GWAS2-DataCollectionA.qmd
            - develop/GWAS2-DataCollection.ipynb
            - develop/GWAS3-QualityControlA.ipynb
        - section: "Quality Control"
          contents:
            - develop/GWAS4-QualityControlB.ipynb
        - section: "Association Testing"
          contents:
            - develop/GWAS5-AssociationTesting.ipynb
            - develop/GWAS6-PRSAnalysis.ipynb
            - develop/GWAS7-OtherToolsAndTesting.ipynb
    - title: "General"
      style: "docked"
      search: true
      contents:
        - href: access/setup.qmd
          text: General
        - section: "Systems"
          contents:
            - access/UCloud.qmd
            - access/genomedk.qmd
            - access/otherHPC.qmd

format:
  html:
    theme: 
      light: [materia, css/materialight.scss]
      dark: darkly
    toc: true
