project:
  type: website

website:
  title: "Genome-Wide Association Studies"
  google-analytics: 
    tracking-id: "G-EXW13D5861"
    anonymize-ip: true
  navbar:
    logo: /img/logo.png
    left:
      - href: index.qmd
        text: Home
      - text: Access
        menu: 
          - href: access/index.qmd
            text: General
          - href: access/UCloud.qmd
            text: UCloud
          - href: access/genomedk.qmd
            text: Genome
      - text: Tutorial
        menu: 
          - href: develop/GWAS1-WhatIsAGWAS.ipynb
            text: What is a GWAS?
          - href: develop/GWAS2-DataCollection.ipynb
            text: Data Collection
          - href: develop/GWAS4-QualityControlB.ipynb
            text: Quality Control B?
          - href: develop/GWAS5-AssociationTesting.ipynb
            text: Association Testing
          - href: develop/GWAS6-PRSAnalysis.ipynb
            text: PRS Analysis
          - href: develop/GWAS7-OtherToolsAndTesting.ipynb
            text: Other tools and testing
 #         - href: develop/GWAS3-QualityControlA.ipynb
 #           text: Quality Control A

format:
  html:
    theme: 
      light: [materia, css/materialight.scss]
      dark: darkly
    toc: true
