---
title: "HPC access"
format:
  html:
    page-layout: full
---


The Sandbox is collaborating with the two major academic high performance computing platforms in Denmark. Computerome is located at the Technical University of Denmark (and co-owned by the University of Copenhagen) while UCloud is owned by the University of Southern Denmark. These HPC platforms each have their own strengths which we leverage in the Sandbox in different ways.

## UCloud

[UCloud](https://cloud.sdu.dk/app/login) is a relatively new HPC platform that can be accessed by students at Danish universities (via a WAYF university login). It has a user friendly graphical user interface that supports straightforward project, user, and resource management. UCloud provides access to many tools via selectable Apps matched with a range of flexible compute resources, and the Sandbox is deploying training modules in this form such that any UCloud user can easily access Sandbox materials independently. The Sandbox is also hosting workshops and training events on UCloud in conjunction with in-person training. 

:::{.callout-tip title="Access Sandbox Apps on UCloud"}
Find detailed instructions on accessing Sandbox apps [here](UCloud.qmd) via UCloud. Check out UCloud's extensive user docs [here](https://docs.cloud.sdu.dk/index.html).  
:::

## GenomeDK

In development.

## Any other computing cluster

In development.

## Your local PC

In development.